#!/bin/sh -e

DOWNLOAD_URL_PREFIX="https://raw.githubusercontent.com/rssnsj/network-feeds/master/ipset-lists"

download_file_of_path() {
	local relpath="$1"
	local file=`basename $relpath`
	echo "Downloading $relpath ..." >&2
	if ! curl -k $DOWNLOAD_URL_PREFIX/$relpath -o $file --interface minivtun-go0; then
		curl -k $DOWNLOAD_URL_PREFIX/$relpath -o $file || return 1
	fi
	echo "Done." >&2
}


mkdir -p /tmp/ipsets-tmp
cd /tmp/ipsets-tmp

# Get checksum and check if we need an update
download_file_of_path tools/MD5SUMS || exit 1
mkdir -p s
cp /etc/ipset/china /etc/gfwlist/china-banned s/
if ! ( cd s && md5sum -c ../MD5SUMS >/dev/null 2>&1 ); then
	download_file_of_path files/etc/ipset/china || exit 1
	download_file_of_path files/etc/gfwlist/china-banned || exit 1
	# File correctness check
	if md5sum -c MD5SUMS; then
		echo "Updating the data files ..."
		cp -f china /etc/ipset/china
		cp -f china-banned /etc/gfwlist/china-banned
		echo "Restarting the services ..."
		[ -x /etc/init.d/minivtun.sh ] && /etc/init.d/minivtun.sh stop || :
		[ -x /etc/init.d/ss-redir.sh ] && /etc/init.d/ss-redir.sh stop || :
		/etc/init.d/ipset.sh restart
		/etc/init.d/minivtun.sh enabled 2>/dev/null && /etc/init.d/minivtun.sh start || :
		/etc/init.d/ss-redir.sh enabled 2>/dev/null && /etc/init.d/ss-redir.sh start || :
		echo "Done."
	else
		echo "*** MD5 mismatch for downloaded files." >&2
	fi
else
	echo "No change on the data."
fi

rm -rf /tmp/ipsets-tmp
