#

SS_SERVER_ADDR=
SS_SERVER_PORT=
SS_SERVER_PASSWORD=
SS_SERVER_METHOD=
SAFE_DNS_SERVER=

# Leave COVERED_SUBNETS, LOCAL_ADDRESSES empty to
# choose subnet addresses of network 'lan' by default
COVERED_SUBNETS=
LOCAL_ADDRESSES=

SS_DISABLED=N
